// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOrRenameFile(arg1, arg2, arg3) {
  return window['go']['app']['common']['CreateOrRenameFile'](arg1, arg2, arg3);
}

export function CreateOrRenameFolder(arg1, arg2, arg3) {
  return window['go']['app']['common']['CreateOrRenameFolder'](arg1, arg2, arg3);
}

export function GetUserConfigData(arg1) {
  return window['go']['app']['common']['GetUserConfigData'](arg1);
}

export function GetUserNoteDirAsTreeData(arg1) {
  return window['go']['app']['common']['GetUserNoteDirAsTreeData'](arg1);
}

export function OpenDir(arg1) {
  return window['go']['app']['common']['OpenDir'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['app']['common']['OpenDirectoryDialog']();
}

export function SaveUserConfigData(arg1, arg2) {
  return window['go']['app']['common']['SaveUserConfigData'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['common']['Startup'](arg1);
}
