// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {util} from '../models';
import {context} from '../models';

export function CreateOrRenameFile(arg1:string,arg2:string,arg3:string):Promise<util.Response>;

export function CreateOrRenameFolder(arg1:string,arg2:string,arg3:string):Promise<util.Response>;

export function GetUserConfigData(arg1:string):Promise<util.Response>;

export function GetUserNoteDirAsTreeData(arg1:string):Promise<util.Response>;

export function OpenDir(arg1:string):Promise<util.Response>;

export function OpenDirectoryDialog():Promise<util.Response>;

export function SaveUserConfigData(arg1:string,arg2:string):Promise<util.Response>;

export function Startup(arg1:context.Context):Promise<void>;
