// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateMarkdown(arg1, arg2) {
  return window['go']['main']['App']['CreateMarkdown'](arg1, arg2);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function ListWorkspace() {
  return window['go']['main']['App']['ListWorkspace']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function ReadMarkdown(arg1) {
  return window['go']['main']['App']['ReadMarkdown'](arg1);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function ResolveImageSource(arg1, arg2) {
  return window['go']['main']['App']['ResolveImageSource'](arg1, arg2);
}

export function SaveAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAttachment'](arg1, arg2, arg3, arg4);
}

export function SaveMarkdown(arg1, arg2) {
  return window['go']['main']['App']['SaveMarkdown'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectAttachmentDirectory(arg1) {
  return window['go']['main']['App']['SelectAttachmentDirectory'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}
