// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFolder(arg1:string,arg2:string):Promise<main.FileNode>;

export function CreateMarkdown(arg1:string,arg2:string):Promise<main.FileNode>;

export function DeletePath(arg1:string):Promise<void>;

export function ListWorkspace():Promise<Array<main.FileNode>>;

export function OpenWorkspace(arg1:string):Promise<main.WorkspaceInfo>;

export function ReadMarkdown(arg1:string):Promise<main.Document>;

export function RenamePath(arg1:string,arg2:string):Promise<main.FileNode>;

export function SaveAttachment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Attachment>;

export function SaveMarkdown(arg1:string,arg2:string):Promise<main.SaveResult>;

export function SelectWorkspace():Promise<main.WorkspaceInfo>;
