// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateMarkdown(arg1, arg2) {
  return window['go']['main']['App']['CreateMarkdown'](arg1, arg2);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function ListWorkspace() {
  return window['go']['main']['App']['ListWorkspace']();
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function ReadMarkdown(arg1) {
  return window['go']['main']['App']['ReadMarkdown'](arg1);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function SaveMarkdown(arg1, arg2) {
  return window['go']['main']['App']['SaveMarkdown'](arg1, arg2);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}
